on: [push]

jobs:
  pack_chromium:
    runs-on: ubuntu-latest
    name: Pack Chromium
    steps:
      - name: Checkout
        uses: actions/checkout

      - name: Gets the Chromium build id
        id: build
        uses: './packages/gh-action'
